### PR TITLE
fix: only apply fix once for the whole file

### LINKED ISSUE #308: rule remark: should fix whole file at a time
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behavior

What should happen?  Please describe the desired behavior.

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

### PR DESCRIPTION
**Pull request by JounQin**
close #308

### CODE REVIEW

**Comment by JounQin** [comment]
@wooorm Please help to review and release for recent updates.

**Review by wooorm — COMMENTED** [review]
I don’t see any weird things — but I don]t feel I know enough about this code base to be sure

**Comment by JounQin** [comment]
@wooorm No worry, we have a lot of test cases to ensure it's just working.

**Comment by wooorm** [comment]
:+1:

I’m waiting for this to be merged, and will cut a new release then, okay?

**Review by ChristianMurphy — APPROVED** [review]

**Comment by JounQin** [comment]
@wooorm Let's go ahead!

**Comment by wooorm** [comment]
Bunch of tests are failing for me when I clone, install, and `yarn test` locally?

**Comment by wooorm** [comment]
Hmm. `yarn build` first I think solved it?

**Comment by wooorm** [comment]
Released!

**Comment by JounQin** [comment]
> Hmm. `yarn build` first I think solved it?

Good to hear, but it seems wired, I'll try to find out and fix this problem soon.

**Comment by wooorm** [comment]
note: I did `yarn` and then `yarn test` (under the assumption that `test` would first build and such). Maybe that assumption is just wrong!

**Comment by JounQin** [comment]
`yarn test` should work without `build`, because we are using `ts-jest`.

I've just found it should be related to `paths` of `tsconfig`.

**Pull request merged**
