### PR TITLE
Add Support for MDX v3

### LINKED ISSUE #480: Incompatible w/ MDX v3?
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.2.0

### Link to runnable example

_No response_

### Steps to reproduce

> Parsing error: Cannot set properties of undefined (setting 'inTable') eslint

Getting [this error](https://github.com/remarkjs/remark-gfm/issues/57) after updating to MDX v3.
- Can someone confirm that eslint-mdx is not yet compatible with MDX v3?

```
"@mdx-js/mdx": "^3.0.0",


        "eslint": "8.54.0",
        "eslint-plugin-mdx": "2.2.0",

        "remark": "^15.0.1",
        "remark-directive": "^3.0.0",
        "remark-frontmatter": "^5.0.0",
        "remark-gfm": "^4.0.0",
        "remark-lint": "^9.1.2",
        "remark-mdx-frontmatter": "^4.0.0",
        "remark-mermaidjs": "^6.0.0",
        "remark-preset-lint-recommended": "^6.1.3",
        "remark-preset-prettier": "^2.0.1",
        "remark-smartypants": "^2.0.0",
```

```
---
Foo: Bar
---

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

Markup on 2023-11-26 at 01:28:43

### Expected behavior

ESLint works propertly using MDX v3.

### Actual behavior

ESLint error:

> Parsing error: Cannot set properties of undefined (setting 'inTable') eslint

### Runtime

Node v19

### Package manager

npm v9

### OS

macOS

### Build and bundle tools

Vite

### PR DESCRIPTION
**Pull request by jaswrks**
@JounQin Thank you. I've smoke tested this just a bit. Seems to do the trick.

- Updated `./package.json` for each of the two packages.
- Updated `Configuration` import from `unified-engine`.

Thanks in advance for anyone able to have a look at this with more experienced eyes than mine.

---

close #480

### CODE REVIEW

**Comment by JounQin** [comment]
CI broken, it seems more changes are required, I'll take a look tomorrow.

**Comment by JounQin** [comment]
https://github.com/mdx-js/eslint-mdx/pull/481/files#diff-28c9951bdd4b9fbbb77321aec606c4ec820dc169ca472ad8991aa553bc4283baR32

@wooorm Any advice about how to migrate like `Root` from `remark-mdx`?

**Comment by JounQin** [comment]
> > Any advice about how to migrate like Root from remark-mdx?
> 
> @JounQin have you tried `Root` from `mdast`? The one in remark-mdx was likely an alias for the one in mdast which was accidentally exported.

It won't work because we need the followings:

image

**Comment by ChristianMurphy** [comment]
@JounQin it will work if `mdast-util-mdx-expression` is included in the ambient types.

See https://www.npmjs.com/package/mdast-util-mdx-expression/v/2.0.0?activeTab=code index.d.ts at around line 120.
It registers the new types on to the root element.

This is how all the mdast parsers register new content types, using content maps, which can be automatically extended parsers so that `mdast` includes the new child types.

**Comment by wooorm** [comment]
See also the readmes, e.g.: https://mdxjs.com/packages/remark-mdx/#types

**Comment by JounQin** [comment]
OK, it seems we need:

```ts
/// <reference types="remark-mdx" />

import type { Root } from 'mdast'
```

I'll try it this night. (Previously, I'm not aware that referencing `remark-mdx` is required).

**Comment by JounQin** [comment]
```log
packages/eslint-mdx/src/tokens.ts:47:7 - error TS2367: This comparison appears to be unintentional because the types '"root" | "paragraph" | "heading" | "thematicBreak" | "blockquote" | "list" | "table" | "html" | "code" | "yaml" | "definition" | "footnoteDefinition" | "listItem" | "tableRow" | ... 12 more ... | "footnoteReference"' and '"mdxFlowExpression"' have no overlap.

47       node.type !== 'mdxFlowExpression' &&
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm still seeing this... @ChristianMurphy @wooorm 

I tried:

```ts
/// <reference types="remark-mdx" />

import type { Root } from 'mdast'
```

Or

```ts
/// <reference types="mdast-util-mdx-expression" />

import type { Root } from 'mdast'
```

**Comment by wooorm** [comment]
You are missing `@types/mdast` as a dependency.
Make sure to specify all the types you include as dependencies, otherwise yarn will fail / pick old versions that don’t work together.

**Pull request closed without merging**
