### PR TITLE
fix: add `prepublishOnly` lifecycle script, close #116

### LINKED ISSUE #116: The package published to npm as v1.6.4 does not include the module code
### Subject of the issue

The package published to npm as v1.6.4 does not include the module code.

image

### PR DESCRIPTION
**Pull request by JounQin**
@mdx-js/releasers

### CODE REVIEW

**Comment by JounQin** [comment]
@mdx-js/releasers Please help to publish `v1.6.5` and deprecated `v1.6.4`.

**Comment by JounQin** [comment]
@mdx-jd/core It seems my permission request for https://codechecks.io/ is still pending?

image

**Comment by wooorm** [comment]
I published 1.6.5.

I think it’s easier if you don’t create a release in Git. As you pushed [1.6.5](https://github.com/mdx-js/eslint-mdx/commit/c9b898d96e8932863fcda1d407cea19135915d47) already, I can’t use yarn to publish to npm anymore.

**Comment by JounQin** [comment]
@wooorm You can always run `npm publish` in correct directories manually without `lerna publish`.

And the key point is that if we have npm publishing on CI correctly, everything will go very well without any pain.

**Comment by wooorm** [comment]
> You can always run npm publish in correct directories manually without lerna publish.

Yeah that’s what I did, but because the build scripts (and now prepublish) are higher, they weren't used

> And the key point is that if we have npm publishing on CI correctly, everything will go very well without any pain.

I still don’t think that’s a good idea, security wise.

**Comment by JounQin** [comment]
@wooorm Personally I would prefer automations for most cases, and releasing hotfixes for very few security conditions.

**Pull request merged**
