### PR TITLE
chore: bump all (dev)Dependencies, update VSCode extension links

### PR DESCRIPTION
**Pull request by JounQin**
Jest snapshot changes: https://github.com/facebook/jest/pull/13036

### CODE REVIEW

**Review by wooorm — APPROVED** [review]
Can you use different PRs in the future? It makes them easier to review.
This is a: too long, didn’t read, but if you’re just bumping dependencies, sure :+1:

**Comment by JounQin** [comment]
Sorry, changing links is too small. 😂

Bumping deps means snapshot has to be updated.

**Comment by wooorm** [comment]
> changing links is too small.

No PR is too small.
Using different PRs means:
a) it is easier for reviewers to review them
b) Git history is clean, bugs can be found better due to an improved `git blame`, commits can be used to generate a changelog entry

For more info, see for example:
* https://www.aleksandrhovhannisyan.com/blog/atomic-git-commits/
* https://www.pauline-vos.nl/atomic-commits/

**Comment by JounQin** [comment]
Thanks for teaching! ❤️

**Pull request merged**
