### PR TITLE
fix: same markdown processor cached for .md and .mdx

### LINKED ISSUE #400: mdx files are linted as markdown if the first processed file is not mdx
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.17.0, 2.0.0-next.5

### Link to runnable example

https://github.com/gyanta/mdxlint_repro

### Steps to reproduce

Run eslint on the example repo and force that the first linted file is / is not an .mdx file

```
yarn eslint README.md src/DEMO.mdx
```

```
yarn eslint src/DEMO.mdx README.md
```

### Expected behavior

A lint error should be reported for both eslint runs

### Actual behavior

The lint error from the `.mdx` file is only reported if the first linted file is `.mdx`

I believe the culprit is here:
https://github.com/mdx-js/eslint-mdx/blob/16c5934530b2f55059dcb7695707f721a693a0d6/packages/eslint-mdx/src/processor.ts#L91

The processor is initialized with or without the `remark-mdx` plugin depending on what the first processed file is, and then the same processor is used for both `.md` and `.mdx` files because the cache key is an empty string.

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

### PR DESCRIPTION
**Pull request by gyanta**
Closes #400

### CODE REVIEW

**Comment by JounQin** [comment]
@gyanta Sorry, please run prettier or `eslint --fix` locally or on [GitPod](https://gitpod.io).

**Review by JounQin — APPROVED** [review]

**Comment by JounQin** [comment]
Thanks for your contribution! @gyanta

**Comment by JounQin** [comment]
@wooorm I believe we can publish a stable v2 version now.

**Comment by JounQin** [comment]
ping @wooorm

**Comment by wooorm** [comment]
I’ll try to get to it tomorrow. Please ping me if I don’t!

**Comment by wooorm** [comment]
Are you sure everything is ready for a stable? `2.0.0`? Exciting!
I am guessing that `yarn release` will make a patch? How do you want me to release it?

**Comment by JounQin** [comment]
> Are you sure everything is ready for a stable? 2.0.0? Exciting!

From my personal view, yes it's! I've been using the beta version for a long time.

> I am guessing that yarn release will make a patch? How do you want me to release it?

I think `yarn release` will just do the right thing.

**Comment by wooorm** [comment]
I think it’s making a next release right now 🤔

**Comment by wooorm** [comment]
```
lerna publish major --conventional-commits --create-release github --yes
```

^-- this probably?

**Comment by JounQin** [comment]
(Lerna seems bad for version management for this point. 😅)

I've migrated to https://github.com/changesets/changesets for most of my projects.

**Comment by JounQin** [comment]
> ```
> lerna publish major --conventional-commits --create-release github --yes
> ```
>
> ^-- this probably?

Maybe, hope it will work correctly. 😅

**Comment by wooorm** [comment]
nope :'(

```
lerna notice cli v4.0.0
lerna info current version 2.0.0-next.6
lerna notice Current HEAD is already released, skipping change detection.
lerna success No changed packages to publish 
```

Is there like a force flag?

**Comment by JounQin** [comment]
@wooorm 

https://github.com/mdx-js/eslint-mdx/pull/396#issuecomment-1126907016

**Comment by JounQin** [comment]
Or force push back the latest commit first to generate a correct changelog?

**Comment by wooorm** [comment]
boom, worked!

**Comment by wooorm** [comment]
Can you manage the release notes?

**Comment by JounQin** [comment]
> Can you manage the release notes?

Yes, just going to do this and change the changelog manually.

**Comment by JounQin** [comment]
Done! https://github.com/mdx-js/eslint-mdx/releases/tag/v2.0.0

**Pull request merged**
