### PR TITLE
feat: resolve custom remark config on parsing

### LINKED ISSUE #336: frontmatter is targeted
### Subject of the issue

Say I have a MDX file with this frontmatter:

<pre>
---
title: Code Splitting
related:
  - title: &lt;link rel="prefetch/preload" > in webpack
    url: https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c
---
</pre>
Note that the `<link >` was not closed.

Now eslint would report `Parsing error: Expected corresponding JSX closing tag for <link>`. Which seems wrong to me. A related comment is here https://github.com/webpack/webpack.js.org/pull/5312#issuecomment-902705944.

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

1. clone https://github.com/webpack/webpack.js.org
2. open `src/content/guides/code-splitting.mdx` and replace the `/>` with `>` in the related part of frontmatter.

FYI, I've tried the latest version https://github.com/mdx-js/eslint-mdx/issues/334#issuecomment-898999220 with no luck.

### Expected behaviour

No error.

### Actual behaviour

An error was shown because frontmatter is targetted.

### PR DESCRIPTION
**Pull request by JounQin**
close #336

### CODE REVIEW

**Review by wooorm — APPROVED** [review]

**Comment by JounQin** [comment]
@wooorm Ready for a new release.

**Comment by wooorm** [comment]
Are the tests supposed to take 150 seconds and more? They seem to hang for me on `remark.test.ts` and `fixtures.test.ts`?

**Comment by wooorm** [comment]
jest is doing this sometimes for me, I’m not sure why. But running yarn again solved it 🤷‍♂️. Released!

**Comment by JounQin** [comment]
> jest is doing this sometimes for me, I’m not sure why. But running yarn again solved it 🤷‍♂️. Released!

The dependencies tree changed a bit in this PR, so `yarn install` is required. 🤣

**Comment by wooorm** [comment]
I never have projects locally, nor yarn, so I installed both freshly though?

**Comment by JounQin** [comment]
Then I'm not sure what is happening too. 🤣

**Pull request merged**
