### PR TITLE
fix: change organization of project repository to mdx-js :tada:

### PR DESCRIPTION
**Pull request by JounQin**

### CODE REVIEW

**Comment by JounQin** [comment]
@wooorm Hi, I'm blocked by `codecov` from merging this PR, would you like to help with this about accepting permission requests of `codecov`?

**Comment by JounQin** [comment]
@ChristianMurphy Thx, but its not about PR approve, I enabled `codecov` check before migrate it into `mdx-js` organization, so can you enable `codecov` for this repository?

image

**Comment by ChristianMurphy** [comment]
@JounQin for now I've made codecov optional to unblock this PR. :heavy_check_mark: 
I'll defer to @wooorm and @johno on enabling codecov.

Personally I prefer using https://jestjs.io/docs/en/configuration#coveragethreshold-object to pass/fail builds, over getting codecov comments on every commit, but that's just me :man_shrugging:

**Comment by wooorm** [comment]
Agreed with Christian. I’m OK with enabling codecov. Will wait for John to enable it, or do it myself in a couple of days!

**Comment by JounQin** [comment]
Actually I've enabled thread already.
https://github.com/mdx-js/eslint-mdx/blob/master/package.json#L63-L74
All 100% coverage 😎

**Comment by JounQin** [comment]
It seems I'm still 'not authorized to merge this pull request', please help to check 
my repository permissions, thx guys.

**Comment by JounQin** [comment]
'The base branch restricts merging to authorized users.'

**Comment by JounQin** [comment]
@johno Would you like to help reviewing my permissions for merging PRs of this repository?

**Comment by wooorm** [comment]
@JounQin I have removed the branch protection rules that were in this repository!

**Comment by JounQin** [comment]
@wooorm Then another question here is that it seems I've lost npm publish permission of `eslint-mdx` and `eslint-plugin-mdx`. I used to publish npm packages with `lerna` automatically. Any advice here? Or can you change the npm token in settings of Travis CI?

**Comment by JounQin** [comment]
@mdx-js/maintainers 

OK, I found out that I'm not a [npm releaser](https://github.com/unifiedjs/collective/blob/master/permissions.md#npm-teams) right now. So would you like to help publishing a new version 1.6.4 of these two packages manually and change the NPM_TOKEN environment in [settings of Travis CI](https://travis-ci.com/mdx-js/eslint-mdx/settings) so that the workflow won't be broken in the future?

**Comment by ChristianMurphy** [comment]
@mdx-js/releasers :point_up:

**Comment by wooorm** [comment]
I'll leave publishing to releasers.

Regarding the token: I'm not sure about using an npm token in Travis to automatically release projects, as it essentially let's anyone with GitHub write access now publish to npm. That's a security problem.
This is a general opinion though, if a project moves fast and isn't used by a lot of people yet, it may be fine 🤷‍♂️

**Comment by JounQin** [comment]
@wooorm That's fine to me, but another question is: is there any releaser interested into this repository and gonna to release them on a schedule.

Besides, another opinion here is that we've guarded codes been merged into `master` branch by mergers, and we can enable only releasing on `master` branch, then why `a security problem` will exist?

**Comment by wooorm** [comment]
I'm sure someone will cut a release soon.

It appears you'd like for releases to happen multiple times a day or every day. That may make sense for this project, but it doesn't make for a very stable ecosystem. MDX is run by volunteers who aren't around every day. Unified is 100s of projects that move at a slower pace because it's been around for years and will be around for years to come. Similar to how React isn't cutting a new release every day either. (Note that the mdx team is free to decide how to do things like this, themselves, it's not a requirement from unified)

Regarding securing master: that was the previous behaviour and you weren't allowed to merge on master. It's the same thing, but making every merger into a releaser.
So the mdx team can change that and secure branches and therefore make every merger a releaser. That is their choice.

**Comment by JounQin** [comment]
@wooorm This repository is stable enough for now, so I'm very open to disable releasing automatically on CI, but also I'm waiting for more responses from other releasers.

**Comment by JounQin** [comment]
@mdx-js/releasers Hey guys, any news here?

**Comment by wooorm** [comment]
Well, I wanted to publish this, but I am unsure how to install this project:

```
tilde in eslint-mdx on master
$ node -v
v13.0.1

tilde in eslint-mdx on master
$ yarn -v
1.13.0

tilde in eslint-mdx on master
$ yarn --frozen-lockfile
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
error Couldn't find a package.json file in "~/oss/eslint-mdx/packages/eslint-mdx/src"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Could you explain to me (or maybe in the docs?) how to collaborate on this project?

**Comment by JounQin** [comment]
@wooorm Would you like to upgrade your `yarrn` version first? It seems much outdated.

**Comment by wooorm** [comment]
Published both packages!

**Pull request merged**
