### PR TITLE
fix: void attribute and empty attribute are different

### LINKED ISSUE #450: Parsing error with <img> tag
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.5

### Link to runnable example

_No response_

### Steps to reproduce

When using the `` tag in a MDX file, certain props results in the error message "Parsing error: Expected value to be truthy" being encountered when linting, despite using the default setup for eslint:

```json
{
  "files": ["*.stories.mdx"],
  "extends": ["plugin:mdx/recommended"]
}
```

Screenshot 2023-02-16 at 13 19 17

If an `` tag only contains `src, `alt` and `title` attributes, then all is good:

```mdx
import { Meta } from '@storybook/addon-docs';

<Meta title="Test" />

# Test

Lorem ipsum dolor sit amet.

<!-- All good -->
<img
  src="https://via.placeholder.com/250x250"
  alt=""
  title=""
/>
```

However, auditing any additional properties, such as `width`, `height`, `loading`, `style`, and also events such as `onClick`, `onLoad`, `onError` (the list is non-exhaustive) will all trigger the same parsing error message. Any props after the line break in the example below will trigger the error:

```mdx
import { Meta } from '@storybook/addon-docs';

<Meta title="Test" />

# Test

Lorem ipsum dolor sit amet.

<img
  src="https://via.placeholder.com/250x250"
  alt=""
  title=""

  className="my-image"
  width={250}
  height={250}
  loading="eager"
  style={{ display: 'block' }}
  onLoad={() => console.log('onLoad')}
  onError={() => console.log('onError')}
  onClick={() => console.log('onClick')}
/>
```

### Expected behavior

Valid uses of `` props and handlers should not trigger eslint parsing error.

### Actual behavior

Valid uses of `` props and handlers triggers eslint parsing error. Attributes that I have tested so far that will _not_ trigger the error:

* `src`
* `srcSet`
* `alt`
* `title`

Attributes that will trigger the error if one or more are present:

* `className`
* `tabIndex`
* `width`
* `height`
* `loading`
* `style`
* `onLoad`
* `onError`
* `onClick`
* &hellip; and more

### Runtime

Node v16

### Package manager

yarn v3

### OS

macOS

### Build and bundle tools

Next.js

### PR DESCRIPTION
**Pull request by JounQin**
close #450

### CODE REVIEW

**Comment by wooorm** [comment]
Looks good but maybe also test a "void" (boolean) attribute too?

**Comment by JounQin** [comment]
> Looks good but maybe also test a "void" (boolean) attribute too?

See https://github.com/mdx-js/eslint-mdx/blob/master/test/fixtures/429.mdx?plain=1

**Comment by wooorm** [comment]
That's a different file.

It's fine that that case exists somewhere.

Because the issue title mentioned void (boolean), I personally expected you test them in this PR.

**Comment by JounQin** [comment]
Done, and found a previous location issue.

**Review by wooorm — APPROVED** [review]

**Pull request merged**
