### PR TITLE
fix: jsx name could be namespace or member expression

### LINKED ISSUE #445: Sub-components as `<Component.SubComponent>` trig eslint errors in MDX files
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.x.x

### Link to runnable example

_No response_

### Steps to reproduce

Create a MDX file with imported Component that have sub-components as:

`doc.mdx`:
```
import { DefinitionList } from `./DefinitionList`

<DefinitionList>
   <DefinitionList.Title>Hello World !</DefinitionList.Title>
<DefinitionList>
```
And `DefinitionList` component:
`DefinitionList.js`:
```
import React from 'react'

export const DefinitionList = ({ children }) => <dl>{children}</dl>
DefinitionList.Title =  ({ children }) => <dt>{children}</dt>
```

### Expected behavior

Should not be any eslint errors

### Actual behavior

On MDX linting (`eslint ./doc.mdx`), we have this error: `error  'DefinitionList.Title' is not defined        react/jsx-no-undef`.

Note: no errors were triggered on last `1.17.1` version.

### Runtime

Node v17

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

webpack

### PR DESCRIPTION
**Pull request by JounQin**
close #445

### CODE REVIEW

**Comment by wooorm** [comment]
I recommend taking this code, it’s well tested!

https://github.com/syntax-tree/hast-util-to-estree/blob/16402511e00cbfb0527efd382e26de6cc7f7eca7/lib/state.js#L323-L370

**Comment by JounQin** [comment]
> I recommend taking this code, it’s well tested!
> 
> https://github.com/syntax-tree/hast-util-to-estree/blob/16402511e00cbfb0527efd382e26de6cc7f7eca7/lib/state.js#L323-L370

Position info is missing there unfortunately.

**Comment by wooorm** [comment]
Hmm, yeah, that’s the case because we don’t know the positional info.

the `jsx-no-undef` rule [only uses the positional info on `node.name`](https://github.com/jsx-eslint/eslint-plugin-react/blob/13f5c1954b5e32f2b97e22d018d0ab276f072b87/lib/rules/jsx-no-undef.js#L111), it doesn’t delve *inside* it.

Would it work if you copy the positional info on `node` (the entire JSX element) onto `node.name`? This would prevent bugs around whitespace/comments/etc

**Comment by JounQin** [comment]
> the jsx-no-undef rule [only uses the positional info on node.name](https://github.com/jsx-eslint/eslint-plugin-react/blob/13f5c1954b5e32f2b97e22d018d0ab276f072b87/lib/rules/jsx-no-undef.js#L111), it doesn’t delve inside it.

I think this fix is more than just fixing that specific issue, it's just representing the correct estree AST.

> Would it work if you copy the positional info on node (the entire JSX element) onto node.name? This would prevent bugs around whitespace/comments/etc

The codes logic is not complex, and I believe it handles `whitespaces` better as described at https://github.com/orgs/mdx-js/discussions/2294.

**Comment by JounQin** [comment]
@wooorm Any further review?

**Comment by wooorm** [comment]
> it's just representing the correct estree AST.

It does. I meant using the algo I linked above, with the addition of setting positional info on `node.name`!

---

But this is fine!

**Pull request merged**
