### PR TITLE
fix: add missing unist-util-visit and vfile deps

### LINKED ISSUE #404: Parsing error: visit is not a function
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0

### Link to runnable example

https://github.com/sudosilico/eslint-mdx-visit-issue

#### Minimal Example

[Minimal repository producing this issue](https://github.com/sudosilico/eslint-mdx-visit-issue) with a fresh Vite / TypeScript / React / Storybook project.

Seems to be the same issue as (#403).

#### Steps taken:

Creating a new project with Vite, TypeScript, React, and Storybook, and then configuring eslint and `eslint-plugin-mdx@2.0.0` results in a `Parsing error: visit is not a function`.

#### Environment:

```
$ yarn --version
1.12.17
$ node --version
v17.3.0
```

M1 MacBook Air 16GB, macOS Monterey 12.3

### Expected behavior

`.mdx` file should should be linted without parsing errors.

### Actual behavior

ESLint gives a parsing error for `.mdx` files:

```
$ eslint --ext .mdx src

...issue-stories/src/stories/Button.stories.mdx
  0:0  error  Parsing error: visit is not a function

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```

### Runtime

Node v17

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Vite

# Workaround:

Downgrading to `eslint-plugin-mdx` version `1.17.0` as seen in commits that reference the above issue seems to resolve this.

### PR DESCRIPTION
**Pull request by JounQin**
close #404

### CODE REVIEW

**Comment by JounQin** [comment]
Ready for a new release @wooorm 

Both v1 and v2, thanks!

**Comment by wooorm** [comment]
Can you land it on v1 too, so that I can release it?

**Comment by JounQin** [comment]
> Can you land it on v1 too, so that I can release it?

v1 does not need this

**Comment by wooorm** [comment]
Oh you meant: release both.
I read it as: release *this* on both! 👍

So you have a recommendation for how to release the v1 branch?

**Comment by wooorm** [comment]
I released v2

**Comment by JounQin** [comment]
> Oh you meant: release both. I read it as: release _this_ on both! 👍
> 
> So you have a recommendation for how to release the v1 branch?

@wooorm 

There is a `release-v1` branch, you release `v1` as usual.

**Comment by wooorm** [comment]
That would likely create a `latest` release on npm?
But I need to release under a different npm tag.
Similar to the `release-next` script.
Or does `yarn release` do that magically?

**Comment by JounQin** [comment]
> That would likely create a `latest` release on npm?
> But I need to release under a different npm tag.
> Similar to the `release-next` script.
> Or does `yarn release` do that magically?

Oh, I forget about that, maybe you update the dist tag in release-v1 branch?

**Comment by wooorm** [comment]
It worked! https://github.com/mdx-js/eslint-mdx/releases

**Pull request merged**
